= UMC PRODUCT API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]

== Admin dashboard

=== 대시보드_action-queue_api_문서화
operation::admin-dashboard-controller-test/대시보드_action-queue_api_문서화[snippets='http-request,http-response']

=== 대시보드_context_api_응답
operation::admin-dashboard-controller-test/대시보드_context_api_응답[snippets='http-request,http-response']

=== 대시보드_operations_api_응답
operation::admin-dashboard-controller-test/대시보드_operations_api_응답[snippets='http-request,http-response']

=== 대시보드_risk-challengers_api_응답
operation::admin-dashboard-controller-test/대시보드_risk-challengers_api_응답[snippets='http-request,http-response']

=== 대시보드_summary_api_문서화
operation::admin-dashboard-controller-test/대시보드_summary_api_문서화[snippets='http-request,http-response']

== Admin school analytics

=== 학교별_summary_api_문서화
operation::admin-school-analytics-controller-test/학교별_summary_api_문서화[snippets='http-request,http-response']

== Admin school query

=== 학교_상세정보를_조회합니다
operation::admin-school-query-controller-test/학교_상세정보를_조회합니다[snippets='http-request,http-response,path-parameters,response-fields']

=== 학교_전체_목록을_조회합니다
operation::admin-school-query-controller-test/학교_전체_목록을_조회합니다[snippets='http-request,http-response,response-fields']

== Challenger workbook command v2

=== workbook-with-submission_delete-returns-conflict
operation::challenger-workbook-command-v2-controller-test/workbook-with-submission_delete-returns-conflict[snippets='http-request,http-response,path-parameters']

== Chapter command

=== 신규_지부를_생성한다
operation::chapter-command-controller-test/신규_지부를_생성한다[snippets='http-request,http-response,request-fields']

== Chapter query

=== 지부_목록을_조회합니다
operation::chapter-query-controller-test/지부_목록을_조회합니다[snippets='http-request,http-response,response-fields']

== Gisu command

=== 기수를_삭제한다
operation::gisu-command-controller-test/기수를_삭제한다[snippets='http-request,http-response,path-parameters']

=== 신규_기수를_추가한다
operation::gisu-command-controller-test/신규_기수를_추가한다[snippets='http-request,http-response,request-fields']

=== 현재_기수를_설정한다
operation::gisu-command-controller-test/현재_기수를_설정한다[snippets='http-request,http-response,path-parameters']

== Gisu query

=== 기수_목록을_페이징_조회한다
operation::gisu-query-controller-test/기수_목록을_페이징_조회한다[snippets='http-request,http-response,query-parameters,response-fields']

=== 기수_전체_목록을_조회한다
operation::gisu-query-controller-test/기수_전체_목록을_조회한다[snippets='http-request,http-response,response-fields']

=== 활성화된_기수를_조회한다
operation::gisu-query-controller-test/활성화된_기수를_조회한다[snippets='http-request,http-response,response-fields']

== Gisu query v2

=== active_false는_400을_반환한다
operation::gisu-query-v2-controller-test/active_false는_400을_반환한다[snippets='http-request,http-response']

=== active_true는_활성_기수만_조회한다
operation::gisu-query-v2-controller-test/active_true는_활성_기수만_조회한다[snippets='http-request,http-response']

=== generation_목록은_중복을_제거하고_조회한다
operation::gisu-query-v2-controller-test/generation_목록은_중복을_제거하고_조회한다[snippets='http-request,http-response']

=== id_목록은_중복을_제거하고_첫_등장_순서대로_조회한다
operation::gisu-query-v2-controller-test/id_목록은_중복을_제거하고_첫_등장_순서대로_조회한다[snippets='http-request,http-response,query-parameters,response-fields']

=== 조회_기준을_둘_이상_보내면_400을_반환한다
operation::gisu-query-v2-controller-test/조회_기준을_둘_이상_보내면_400을_반환한다[snippets='http-request,http-response']

=== 조회_기준이_없으면_400을_반환한다
operation::gisu-query-v2-controller-test/조회_기준이_없으면_400을_반환한다[snippets='http-request,http-response']

== Recruiting admin

=== close-form-endpoint-is-removed
operation::recruiting-admin-controller-test/close-form-endpoint-is-removed[snippets='http-request,http-response']

=== csv_export_api는_raw_email과_지원서_본문_없이_attachment를_반환한다
operation::recruiting-admin-controller-test/csv_export_api는_raw_email과_지원서_본문_없이_attachment를_반환한다[snippets='http-request,http-response']

=== publish-form-endpoint-is-removed
operation::recruiting-admin-controller-test/publish-form-endpoint-is-removed[snippets='http-request,http-response']

=== ready-uses-current-member-actor
operation::recruiting-admin-controller-test/ready-uses-current-member-actor[snippets='http-request,http-response']

=== 면접_생략_api는_-current-member와_사유를_전달한다
operation::recruiting-admin-controller-test/면접_생략_api는_-current-member와_사유를_전달한다[snippets='http-request,http-response']

=== 면접_생략_api는_긴_사유를_거부한다
operation::recruiting-admin-controller-test/면접_생략_api는_긴_사유를_거부한다[snippets='http-request,http-response']

=== 모집_폼_upsert_api는_전체_구조와_요청자를_전달한다
operation::recruiting-admin-controller-test/모집_폼_upsert_api는_전체_구조와_요청자를_전달한다[snippets='http-request,http-response']

=== 상태_요약_api는_status별_count를_반환한다
operation::recruiting-admin-controller-test/상태_요약_api는_status별_count를_반환한다[snippets='http-request,http-response']

=== 서류_결정_api는_결정자와_합불을_전달한다
operation::recruiting-admin-controller-test/서류_결정_api는_결정자와_합불을_전달한다[snippets='http-request,http-response']

=== 서류_결정_api는_긴_사유를_거부한다
operation::recruiting-admin-controller-test/서류_결정_api는_긴_사유를_거부한다[snippets='http-request,http-response']

=== 최종_결정_api는_결정자_member-id를_command로_전달한다
operation::recruiting-admin-controller-test/최종_결정_api는_결정자_member-id를_command로_전달한다[snippets='http-request,http-response']

=== 평가_이력_csv_api는_attachment를_반환한다
operation::recruiting-admin-controller-test/평가_이력_csv_api는_attachment를_반환한다[snippets='http-request,http-response']

=== 평가_이력_csv_api는_빈_chapter-ids_반복_값을_거부한다
operation::recruiting-admin-controller-test/평가_이력_csv_api는_빈_chapter-ids_반복_값을_거부한다[snippets='http-request,http-response']

=== 평가_이력_csv_api는_빈_chapter-ids를_거부한다
operation::recruiting-admin-controller-test/평가_이력_csv_api는_빈_chapter-ids를_거부한다[snippets='http-request,http-response']

=== 평가_이력_csv_api는_빈_school-ids_반복_값을_거부한다
operation::recruiting-admin-controller-test/평가_이력_csv_api는_빈_school-ids_반복_값을_거부한다[snippets='http-request,http-response']

=== 평가_이력_csv_api는_빈_school-ids를_거부한다
operation::recruiting-admin-controller-test/평가_이력_csv_api는_빈_school-ids를_거부한다[snippets='http-request,http-response']

=== 평가_이력_csv_api는_유효하지_않은_반복_id를_거부한다
operation::recruiting-admin-controller-test/평가_이력_csv_api는_유효하지_않은_반복_id를_거부한다[snippets='http-request,http-response']

=== 평가_이력_조회_api는_빈_chapter-ids_반복_값을_거부한다
operation::recruiting-admin-controller-test/평가_이력_조회_api는_빈_chapter-ids_반복_값을_거부한다[snippets='http-request,http-response']

=== 평가_이력_조회_api는_빈_chapter-ids를_거부한다
operation::recruiting-admin-controller-test/평가_이력_조회_api는_빈_chapter-ids를_거부한다[snippets='http-request,http-response']

=== 평가_이력_조회_api는_빈_school-ids_반복_값을_거부한다
operation::recruiting-admin-controller-test/평가_이력_조회_api는_빈_school-ids_반복_값을_거부한다[snippets='http-request,http-response']

=== 평가_이력_조회_api는_빈_school-ids를_거부한다
operation::recruiting-admin-controller-test/평가_이력_조회_api는_빈_school-ids를_거부한다[snippets='http-request,http-response']

=== 평가_이력_조회_api는_유효하지_않은_반복_id를_거부한다
operation::recruiting-admin-controller-test/평가_이력_조회_api는_유효하지_않은_반복_id를_거부한다[snippets='http-request,http-response']

=== 평가_이력_조회_api는_조건을_query로_전달한다
operation::recruiting-admin-controller-test/평가_이력_조회_api는_조건을_query로_전달한다[snippets='http-request,http-response']

=== 평가_현황_집계_api는_지부_학교_파트별_카운트를_반환한다
operation::recruiting-admin-controller-test/평가_현황_집계_api는_지부_학교_파트별_카운트를_반환한다[snippets='http-request,http-response']

== Recruiting application

=== get-my-applications-uses-authenticated-member
operation::recruiting-application-controller-test/get-my-applications-uses-authenticated-member[snippets='http-request,http-response']

=== create-draft-uses-authenticated-actor
operation::recruiting-application-controller-test/create-draft-uses-authenticated-actor[snippets='http-request,http-response']

=== reject-malformed-email-when-other-create-fields-are-valid
operation::recruiting-application-controller-test/reject-malformed-email-when-other-create-fields-are-valid[snippets='http-request,http-response']

=== reject-non-positive-form-id-when-other-create-fields-are-valid
operation::recruiting-application-controller-test/reject-non-positive-form-id-when-other-create-fields-are-valid[snippets='http-request,http-response']

=== reject-unauthenticated-create
operation::recruiting-application-controller-test/reject-unauthenticated-create[snippets='http-request,http-response']

== Recruiting application mutation

=== cancel-uses-authenticated-actor
operation::recruiting-application-mutation-controller-test/cancel-uses-authenticated-actor[snippets='http-request,http-response']

=== reject-malformed-email-when-other-update-fields-are-valid
operation::recruiting-application-mutation-controller-test/reject-malformed-email-when-other-update-fields-are-valid[snippets='http-request,http-response']

=== reject-non-positive-application-id
operation::recruiting-application-mutation-controller-test/reject-non-positive-application-id[snippets='http-request,http-response']

=== reject-non-positive-question-id-when-other-update-fields-are-valid
operation::recruiting-application-mutation-controller-test/reject-non-positive-question-id-when-other-update-fields-are-valid[snippets='http-request,http-response']

=== submit-uses-authenticated-actor
operation::recruiting-application-mutation-controller-test/submit-uses-authenticated-actor[snippets='http-request,http-response']

=== update-draft-uses-authenticated-actor
operation::recruiting-application-mutation-controller-test/update-draft-uses-authenticated-actor[snippets='http-request,http-response']

== Recruiting public

=== public-round-list-binds-filters
operation::recruiting-public-controller-test/public-round-list-binds-filters[snippets='http-request,http-response']

=== 익명_지원서_생성_api는_지원_키를_최초_응답에서_반환한다
operation::recruiting-public-controller-test/익명_지원서_생성_api는_지원_키를_최초_응답에서_반환한다[snippets='http-request,http-response']

=== 익명_지원서_조회_api는_내부_key를_노출하지_않는다
operation::recruiting-public-controller-test/익명_지원서_조회_api는_내부_key를_노출하지_않는다[snippets='http-request,http-response']

=== 익명_지원서_철회_api는_정규화된_credential을_전달한다
operation::recruiting-public-controller-test/익명_지원서_철회_api는_정규화된_credential을_전달한다[snippets='http-request,http-response']

== School command

=== 총괄_신규학교를_추가한다
operation::school-command-controller-test/총괄_신규학교를_추가한다[snippets='http-request,http-response,request-fields']

=== 총괄_학교를_일괄_삭제한다
operation::school-command-controller-test/총괄_학교를_일괄_삭제한다[snippets='http-request,http-response,request-fields']

=== 총괄_학교정보를_수정한다
operation::school-command-controller-test/총괄_학교정보를_수정한다[snippets='http-request,http-response,path-parameters,request-fields']

== School link query

=== 학교_링크를_조회합니다
operation::school-link-query-controller-test/학교_링크를_조회합니다[snippets='http-request,http-response,path-parameters,response-fields']

== System status

=== 점검중이_아닐_때_in-maintenance_false
operation::system-status-controller-test/점검중이_아닐_때_in-maintenance_false[snippets='http-request,http-response']

=== 점검중일_때_current_채워짐
operation::system-status-controller-test/점검중일_때_current_채워짐[snippets='http-request,http-response']

== Umc product chapter controller documentation test

=== umc_product_-chapter_목록을_조회한다
operation::umc-product-chapter-controller-documentation-test/umc_product_-chapter_목록을_조회한다[snippets='http-request,http-response,query-parameters']

=== umc_product_-chapter를_삭제한다
operation::umc-product-chapter-controller-documentation-test/umc_product_-chapter를_삭제한다[snippets='http-request,http-response,path-parameters']

=== umc_product_-chapter를_생성한다
operation::umc-product-chapter-controller-documentation-test/umc_product_-chapter를_생성한다[snippets='http-request,http-response,request-fields']

=== umc_product_-chapter를_수정한다
operation::umc-product-chapter-controller-documentation-test/umc_product_-chapter를_수정한다[snippets='http-request,http-response,path-parameters,request-fields']

=== 제거된_umc_product_-part_api는_404를_반환한다
operation::umc-product-chapter-controller-documentation-test/제거된_umc_product_-part_api는_404를_반환한다[snippets='http-request,http-response']

== Umc product member command controller documentation test

=== umc_product_-leadership을_삭제한다
operation::umc-product-member-command-controller-documentation-test/umc_product_-leadership을_삭제한다[snippets='http-request,http-response,path-parameters']

=== umc_product_-leadership을_생성한다
operation::umc-product-member-command-controller-documentation-test/umc_product_-leadership을_생성한다[snippets='http-request,http-response,path-parameters,request-fields']

=== umc_product_-leadership을_수정한다
operation::umc-product-member-command-controller-documentation-test/umc_product_-leadership을_수정한다[snippets='http-request,http-response,path-parameters,request-fields']

=== umc_product_멤버_-chapter_소속을_삭제한다
operation::umc-product-member-command-controller-documentation-test/umc_product_멤버_-chapter_소속을_삭제한다[snippets='http-request,http-response,path-parameters']

=== umc_product_멤버_-chapter_소속을_생성한다
operation::umc-product-member-command-controller-documentation-test/umc_product_멤버_-chapter_소속을_생성한다[snippets='http-request,http-response,path-parameters,request-fields']

=== umc_product_멤버_-chapter_소속을_수정한다
operation::umc-product-member-command-controller-documentation-test/umc_product_멤버_-chapter_소속을_수정한다[snippets='http-request,http-response,path-parameters,request-fields']

=== umc_product_멤버_프로필을_수정한다
operation::umc-product-member-command-controller-documentation-test/umc_product_멤버_프로필을_수정한다[snippets='http-request,http-response,path-parameters,request-fields']

=== umc_product_멤버_활동_기간을_삭제한다
operation::umc-product-member-command-controller-documentation-test/umc_product_멤버_활동_기간을_삭제한다[snippets='http-request,http-response,path-parameters']

=== umc_product_멤버_활동_기간을_생성한다
operation::umc-product-member-command-controller-documentation-test/umc_product_멤버_활동_기간을_생성한다[snippets='http-request,http-response,path-parameters,request-fields']

=== umc_product_멤버_활동_기간을_수정한다
operation::umc-product-member-command-controller-documentation-test/umc_product_멤버_활동_기간을_수정한다[snippets='http-request,http-response,path-parameters,request-fields']

=== umc_product_멤버를_삭제한다
operation::umc-product-member-command-controller-documentation-test/umc_product_멤버를_삭제한다[snippets='http-request,http-response,path-parameters']

=== umc_product_멤버를_생성한다
operation::umc-product-member-command-controller-documentation-test/umc_product_멤버를_생성한다[snippets='http-request,http-response,request-fields']

=== 제거된_umc_product_-part_소속_api는_404를_반환한다
operation::umc-product-member-command-controller-documentation-test/제거된_umc_product_-part_소속_api는_404를_반환한다[snippets='http-request,http-response']

== Umc product member query controller documentation test

=== umc_product_멤버_상세를_조회한다
operation::umc-product-member-query-controller-documentation-test/umc_product_멤버_상세를_조회한다[snippets='http-request,http-response,path-parameters']

=== umc_product_멤버를_검색한다
operation::umc-product-member-query-controller-documentation-test/umc_product_멤버를_검색한다[snippets='http-request,http-response,query-parameters']

=== 시각이_포함된_활동_기준일을_거부한다
operation::umc-product-member-query-controller-documentation-test/시각이_포함된_활동_기준일을_거부한다[snippets='http-request,http-response']

== Umc product organization chart query controller documentation test

=== 현재_umc_product_조직도를_조회한다
operation::umc-product-organization-chart-query-controller-documentation-test/현재_umc_product_조직도를_조회한다[snippets='http-request,http-response']

== Umc product squad controller documentation test

=== umc_product_-squad_목록을_조회한다
operation::umc-product-squad-controller-documentation-test/umc_product_-squad_목록을_조회한다[snippets='http-request,http-response,query-parameters']

=== umc_product_-squad_참여를_삭제한다
operation::umc-product-squad-controller-documentation-test/umc_product_-squad_참여를_삭제한다[snippets='http-request,http-response,path-parameters']

=== umc_product_-squad_참여를_생성한다
operation::umc-product-squad-controller-documentation-test/umc_product_-squad_참여를_생성한다[snippets='http-request,http-response,path-parameters,request-fields']

=== umc_product_-squad_참여를_수정한다
operation::umc-product-squad-controller-documentation-test/umc_product_-squad_참여를_수정한다[snippets='http-request,http-response,path-parameters,request-fields']

=== umc_product_-squad를_삭제한다
operation::umc-product-squad-controller-documentation-test/umc_product_-squad를_삭제한다[snippets='http-request,http-response,path-parameters']

=== umc_product_-squad를_생성한다
operation::umc-product-squad-controller-documentation-test/umc_product_-squad를_생성한다[snippets='http-request,http-response,request-fields']

=== umc_product_-squad를_수정한다
operation::umc-product-squad-controller-documentation-test/umc_product_-squad를_수정한다[snippets='http-request,http-response,path-parameters,request-fields']

=== 제거된_-squad_참여자_전체_교체_api는_404를_반환한다
operation::umc-product-squad-controller-documentation-test/제거된_-squad_참여자_전체_교체_api는_404를_반환한다[snippets='http-request,http-response']

== Workbook query v2

=== best-workbook_size101-rejected
operation::workbook-query-v2-controller-test/best-workbook_size101-rejected[snippets='http-request,http-response']

=== best-workbook_without-gisu-returns-page-response
operation::workbook-query-v2-controller-test/best-workbook_without-gisu-returns-page-response[snippets='http-request,http-response,query-parameters']

=== challenger-workbook_passes-requester-member-id
operation::workbook-query-v2-controller-test/challenger-workbook_passes-requester-member-id[snippets='http-request,http-response,path-parameters']

=== original-workbook_passes-requester-member-id
operation::workbook-query-v2-controller-test/original-workbook_passes-requester-member-id[snippets='http-request,http-response,path-parameters']
