interface Form {
  title: String!
  description: String
  sections: [FormSection!]!
}

interface FormSection {
  sectionId: ID!
  title: String!
  description: String
  orderNo: Int!
  questions: [FormQuestion!]!
}

type FormQuestion {
  questionId: ID!
  type: QuestionType!
  title: String!
  description: String
  required: Boolean!
  orderNo: Int!
  options: [FormOption!]!
}

type FormOption {
  optionId: ID!
  content: String!
  orderNo: Int!
  other: Boolean!
}

enum FormStatus {
  DRAFT
  PUBLISHED
}

enum FormResponseStatus {
  DRAFT
  SUBMITTED
}

enum QuestionType {
  SHORT_TEXT
  LONG_TEXT
  RADIO
  CHECKBOX
  DROPDOWN
  SCHEDULE
  FILE
  PORTFOLIO
}
