extend type Query {
  me: Member!
  member(id: ID!): Member
  members(filter: MemberFilterInput, first: Int, after: String, last: Int, before: String): MemberSearchResultConnection!
}

input MemberFilterInput {
  keyword: String
  gisuId: ID
  part: ChallengerPart
  chapterId: ID
  schoolId: ID
}

type MemberSearchResultConnection {
  edges: [MemberSearchResultEdge!]!
  pageInfo: PageInfo!
  totalCount: Long!
}

type MemberSearchResultEdge {
  cursor: String!
  node: MemberSearchResult!
}

type MemberSearchResult {
  memberId: ID!
  name: String
  nickname: String
  email: String
  school: School
  profileImageLink: String
  currentChallenger: MemberSearchChallenger
  isAdminInActiveGisu: Boolean!
  challengerRecords: [MemberSearchChallenger!]!
}

type MemberSearchChallenger {
  challengerId: ID!
  gisu: Gisu
  generation: Int!
  part: ChallengerPart!
  challengerStatus: ChallengerStatus!
}

type Member implements Node {
  id: ID!
  name: String
  nickname: String
  email: String
  profileImageLink: String
  status: MemberStatus
  school: School
  challengers: [MemberChallenger!]!
}

enum MemberStatus {
  ACTIVE
  INACTIVE
  WITHDRAWN
}

type MemberChallenger {
  challengerId: ID!
  gisu: Gisu
  part: ChallengerPart
  tracks: [ChallengerTrack!]!
  status: ChallengerStatus!
}

enum ChallengerStatus {
  ACTIVE
  GRADUATED
  EXPELLED
  WITHDRAWN
}
