extend type Query {
  gisus(filter: GisuFilterInput, first: Int, after: String, last: Int, before: String): GisuConnection!
  gisu(id: ID!): Gisu!
  activeGisu: Gisu!
  chapters(first: Int, after: String, last: Int, before: String): ChapterConnection!
  chapter(id: ID!): Chapter!
  schools(first: Int, after: String, last: Int, before: String): SchoolNameConnection!
  school(id: ID!): School!
}

"""
기수 목록 조회 조건. ids / generations / active 중 정확히 하나만 지정해야 한다.
"""
input GisuFilterInput {
  ids: [ID!]
  generations: [Int!]
  active: Boolean
}

type GisuConnection {
  edges: [GisuEdge!]!
  pageInfo: PageInfo!
  totalCount: Long!
}

type GisuEdge {
  cursor: String!
  node: Gisu!
}

type Gisu implements Node {
  id: ID!
  generation: Int!
  startAt: String!
  endAt: String!
  active: Boolean!
  chapters: [GisuChapter!]!
  schools: [GisuSchool!]!
}

type GisuChapter {
  chapterId: ID!
  chapterName: String!
  schools: [ChapterSchool!]!
}

type ChapterSchool {
  schoolId: ID!
  schoolName: String!
}

type GisuSchool {
  chapterId: ID
  chapterName: String
  schoolId: ID!
  schoolName: String!
  remark: String
  logoImageUrl: String
  links: [SchoolLink!]!
  active: Boolean!
  createdAt: String!
  updatedAt: String!
}

type ChapterConnection {
  edges: [ChapterEdge!]!
  pageInfo: PageInfo!
  totalCount: Long!
}

type ChapterEdge {
  cursor: String!
  node: Chapter!
}

type Chapter implements Node {
  id: ID!
  name: String!
}

type SchoolNameConnection {
  edges: [SchoolNameEdge!]!
  pageInfo: PageInfo!
  totalCount: Long!
}

type SchoolNameEdge {
  cursor: String!
  node: SchoolName!
}

type SchoolName {
  schoolId: ID!
  schoolName: String!
}

type School implements Node {
  id: ID!
  chapterId: ID
  chapterName: String
  schoolName: String!
  remark: String
  logoImageUrl: String
  links: [SchoolLink!]!
  active: Boolean!
  createdAt: String!
  updatedAt: String!
}

type SchoolLink {
  title: String
  type: SchoolLinkType!
  url: String!
}

enum SchoolLinkType {
  KAKAO
  YOUTUBE
  INSTAGRAM
}
