type Query {
  gisuOrganizations(input: GisuOrganizationInput!): GisuOrganizationPayload!
  gisu(id: ID!): Gisu!
  activeGisu: Gisu!
  chapters: [Chapter!]!
  chapter(id: ID!): Chapter!
  schools: [School!]!
  school(id: ID!): School!
}

input GisuOrganizationInput {
  ids: [ID!]
  generations: [ID!]
  active: Boolean
}

type GisuOrganizationPayload {
  gisus: [Gisu!]!
}

type Gisu {
  id: ID!
  generation: ID!
  startAt: String!
  endAt: String!
  active: Boolean!
  chapters: [Chapter!]!
  schools: [School!]!
}

type Chapter {
  id: ID!
  name: String!
  schools: [School!]!
}

type School {
  id: ID!
  name: String!
  remark: String
  logoImageUrl: String
  links: [SchoolLink!]!
  active: Boolean!
  createdAt: String!
  updatedAt: String!
}

type SchoolLink {
  title: String
  type: SchoolLinkType!
  url: String!
}

enum SchoolLinkType {
  KAKAO
  YOUTUBE
  INSTAGRAM
}
