package com.umc.product.authorization.domain.policy;

public enum PolicyEvaluationFailureCode {
    ACTION_NOT_REGISTERED,
    REQUIRED_ATTRIBUTE_MISSING,
    ATTRIBUTE_NOT_REGISTERED,
    ATTRIBUTE_TYPE_MISMATCH,
    ATTRIBUTE_ENUM_SYMBOL_UNKNOWN,
    OUTCOME_ATTRIBUTE_MISSING,
    OUTCOME_VALUE_UNSUPPORTED,
    EXACTLY_ONE_CONFLICT
}
