"""Gisu 조직도 조회 결과."""
type GisuOrganizationPayload {
  gisus: [Gisu!]!
}

"""Organization 도메인이 표준으로 제공하는 기수 응답."""
type Gisu {
  id: ID!
  """사람이 인식하는 기수 번호."""
  generation: ID!
  startAt: String!
  endAt: String!
  active: Boolean!
  """이 Gisu에 편성된 Chapter 목록."""
  chapters: [Chapter!]!
  """이 Gisu에 참여한 School 목록."""
  schools: [School!]!
}

"""Organization 도메인이 표준으로 제공하는 지부 응답."""
type Chapter {
  id: ID!
  name: String!
  """이 Chapter에 소속된 School 목록."""
  schools: [School!]!
}

"""Organization 도메인이 표준으로 제공하는 학교 응답."""
type School {
  id: ID!
  name: String!
  remark: String
  logoImageUrl: String
  links: [SchoolLink!]!
  active: Boolean!
  createdAt: String!
  updatedAt: String!
}

"""School의 외부 채널 링크."""
type SchoolLink {
  title: String
  type: SchoolLinkType!
  url: String!
}

"""School 외부 채널 종류."""
enum SchoolLinkType {
  KAKAO
  YOUTUBE
  INSTAGRAM
}
