package com.umc.product.notification.domain;

public enum EmailTemplateType {
    RECRUITMENT_DOCUMENT_PASSED_INTERVIEW_AVAILABILITY_REQUEST,
    RECRUITMENT_INTERVIEW_CONFIRMATION,
    RECRUITMENT_FINAL_PASSED,
    RECRUITMENT_FINAL_FAILED
}
