package com.umc.product.registry.domain;

public enum RegistryCutoverMilestone {
    SCHEMA_EXPAND_ARTIFACT,
    STORAGE_MAINTENANCE_START,
    DUAL_WRITER_ROLLING_DEPLOY,
    OLD_POD_DRAIN_AND_VERSION_CHECK,
    STORAGE_MAINTENANCE_END,
    KEYSET_BACKFILL,
    PRIMARY_REPLICA_FOUR_DRIFT_ZERO,
    ROLLBACK_WINDOW_END,
    CONTRACT_00_40,
    FINAL_RECONCILE,
    THREE_REGISTRIES_READY,
    PROPERTIES_ENABLE
}
