DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.recruiting_application LIMIT 1)
        OR EXISTS (SELECT 1 FROM public.recruiting_application_form LIMIT 1) THEN
        RAISE EXCEPTION USING
            ERRCODE = 'P0001',
            MESSAGE = 'V2026.07.12.17.00 aborted: recruiting_application and recruiting_application_form must be empty before destructive Recruiting v2 remodeling';
    END IF;
END
$$;

TRUNCATE TABLE public.recruiting_application_form, public.recruiting_application
    RESTART IDENTITY CASCADE;

DROP INDEX IF EXISTS public.uk_recruiting_application_active_round_identity;

ALTER TABLE public.recruiting_application_form
    DROP CONSTRAINT IF EXISTS uk_recruiting_application_form_round_form,
    DROP CONSTRAINT IF EXISTS recruiting_application_form_track_check,
    DROP COLUMN IF EXISTS track,
    ADD CONSTRAINT uk_recruiting_application_form_round UNIQUE (recruiting_round_id);

ALTER TABLE public.recruiting_application
    DROP CONSTRAINT IF EXISTS uk_recruiting_application_application_no,
    DROP COLUMN IF EXISTS applicant_identity_key,
    DROP COLUMN IF EXISTS application_no,
    DROP COLUMN IF EXISTS masked_email,
    ADD COLUMN applicant_name VARCHAR(100) NOT NULL,
    ADD COLUMN applicant_email VARCHAR(255) NOT NULL,
    ADD COLUMN first_choice VARCHAR(255) NOT NULL,
    ADD COLUMN second_choice VARCHAR(255),
    ADD COLUMN privacy_term_id BIGINT,
    ADD COLUMN privacy_agreed_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN application_key VARCHAR(6) NOT NULL,
    ADD COLUMN accepted_track VARCHAR(255),
    ADD CONSTRAINT uk_recruiting_application_round_email
        UNIQUE (recruiting_round_id, applicant_email),
    ADD CONSTRAINT uk_recruiting_application_round_member
        UNIQUE (recruiting_round_id, applicant_member_id),
    ADD CONSTRAINT uk_recruiting_application_email_key
        UNIQUE (applicant_email, application_key),
    ADD CONSTRAINT recruiting_application_name_check
        CHECK (applicant_name <> '' AND applicant_name !~ '[[:space:]]'),
    ADD CONSTRAINT recruiting_application_email_normalized_check
        CHECK (
            applicant_email = LOWER(BTRIM(applicant_email))
            AND LENGTH(applicant_email) <= 254
            AND LENGTH(SPLIT_PART(applicant_email, '@', 1)) <= 64
            AND applicant_email ~
                '^[a-z0-9!#$%&''*+/=?^_`{|}~-]+([.][a-z0-9!#$%&''*+/=?^_`{|}~-]+)*@[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?([.][a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$'
        ),
    ADD CONSTRAINT recruiting_application_key_check
        CHECK (application_key ~ '^[A-Z0-9]{6}$'),
    ADD CONSTRAINT recruiting_application_choice_track_check
        CHECK (
            first_choice IN ('PLAN', 'DESIGN', 'WEB_PRODUCT_ENGINEER', 'MOBILE_PRODUCT_ENGINEER')
            AND (
                second_choice IS NULL
                OR second_choice IN ('PLAN', 'DESIGN', 'WEB_PRODUCT_ENGINEER', 'MOBILE_PRODUCT_ENGINEER')
            )
            AND second_choice IS DISTINCT FROM first_choice
        ),
    ADD CONSTRAINT recruiting_application_privacy_check
        CHECK (
            (privacy_term_id IS NULL AND privacy_agreed_at IS NULL)
            OR (privacy_term_id IS NOT NULL AND privacy_agreed_at IS NOT NULL)
        ),
    ADD CONSTRAINT recruiting_application_accepted_track_check
        CHECK (
            accepted_track IS NULL
            OR accepted_track = first_choice
            OR accepted_track = second_choice
        );

CREATE TABLE public.recruiting_form_section_policy
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                      TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at                      TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_application_form_id BIGINT                                  NOT NULL,
    form_section_id                 BIGINT                                  NOT NULL,
    type                            VARCHAR(255)                            NOT NULL,
    track                           VARCHAR(255),
    CONSTRAINT pk_recruiting_form_section_policy PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_form_section_policy_form_section UNIQUE (form_section_id),
    CONSTRAINT fk_recruiting_form_section_policy_application_form
        FOREIGN KEY (recruiting_application_form_id) REFERENCES public.recruiting_application_form (id),
    CONSTRAINT recruiting_form_section_policy_type_check
        CHECK (type IN ('COMMON', 'TRACK')),
    CONSTRAINT recruiting_form_section_policy_track_check
        CHECK (
            (type = 'COMMON' AND track IS NULL)
            OR (
                type = 'TRACK'
                AND track IS NOT NULL
                AND track IN ('PLAN', 'DESIGN', 'WEB_PRODUCT_ENGINEER', 'MOBILE_PRODUCT_ENGINEER')
            )
        )
);

CREATE INDEX ix_recruiting_form_section_policy_application_form
    ON public.recruiting_form_section_policy (recruiting_application_form_id);
