ALTER TABLE public.file_metadata
    ADD COLUMN confirmed_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN unreferenced_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN cleanup_claim_token UUID,
    ADD COLUMN cleanup_claimed_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN cleanup_attempts INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN cleanup_next_attempt_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN cleanup_failed_at TIMESTAMP(6) WITH TIME ZONE;

CREATE INDEX idx_file_metadata_cleanup_candidate
    ON public.file_metadata (cleanup_next_attempt_at, unreferenced_at, confirmed_at, created_at)
    WHERE cleanup_failed_at IS NULL;

CREATE TABLE public.file_usage_owner
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usage_namespace VARCHAR(100)                NOT NULL,
    resource_key    VARCHAR(128)                NOT NULL,
    slot            VARCHAR(50)                 NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_file_usage_owner_coordinate
        UNIQUE (usage_namespace, resource_key, slot),
    CONSTRAINT ck_file_usage_owner_namespace
        CHECK (usage_namespace ~ '^[a-z][a-z0-9-]{0,31}(\.[a-z][a-z0-9-]{0,31})*$'),
    CONSTRAINT ck_file_usage_owner_resource_key
        CHECK (resource_key ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'),
    CONSTRAINT ck_file_usage_owner_slot
        CHECK (slot ~ '^[a-z][a-z0-9-]{0,49}$')
);

CREATE TABLE public.file_usage
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT                      NOT NULL,
    file_id    VARCHAR(255)                NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_file_usage_owner_file UNIQUE (owner_id, file_id),
    CONSTRAINT fk_file_usage_owner
        FOREIGN KEY (owner_id) REFERENCES public.file_usage_owner (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_usage_metadata
        FOREIGN KEY (file_id) REFERENCES public.file_metadata (id) ON DELETE RESTRICT
);

CREATE INDEX idx_file_usage_file_id ON public.file_usage (file_id);
