CREATE TABLE public.recruiting_round_evaluator
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_round_id  BIGINT                                  NOT NULL,
    member_id            BIGINT                                  NOT NULL,
    stage                VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_recruiting_round_evaluator PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_round_evaluator_round_member_stage UNIQUE (
        recruiting_round_id,
        member_id,
        stage
    ),
    CONSTRAINT recruiting_round_evaluator_stage_check CHECK (stage IN ('DOCUMENT', 'INTERVIEW'))
);

CREATE TABLE public.recruiting_round_interview_question
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_round_id  BIGINT                                  NOT NULL,
    content              TEXT                                    NOT NULL,
    order_no             INTEGER                                 NOT NULL,
    active               BOOLEAN                                 NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_recruiting_round_interview_question PRIMARY KEY (id),
    CONSTRAINT recruiting_round_interview_question_content_check CHECK (length(btrim(content)) > 0),
    CONSTRAINT recruiting_round_interview_question_order_no_check CHECK (order_no >= 0)
);

CREATE TABLE public.recruiting_application_interview_question
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                  TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at                  TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_application_id  BIGINT                                  NOT NULL,
    content                     TEXT                                    NOT NULL,
    order_no                    INTEGER                                 NOT NULL,
    active                      BOOLEAN                                 NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_recruiting_application_interview_question PRIMARY KEY (id),
    CONSTRAINT recruiting_application_interview_question_content_check CHECK (length(btrim(content)) > 0),
    CONSTRAINT recruiting_application_interview_question_order_no_check CHECK (order_no >= 0)
);

ALTER TABLE public.recruiting_round_evaluator
    ADD CONSTRAINT fk_recruiting_round_evaluator_round
        FOREIGN KEY (recruiting_round_id) REFERENCES public.recruiting_round (id);

ALTER TABLE public.recruiting_round_interview_question
    ADD CONSTRAINT fk_recruiting_round_interview_question_round
        FOREIGN KEY (recruiting_round_id) REFERENCES public.recruiting_round (id);

ALTER TABLE public.recruiting_application_interview_question
    ADD CONSTRAINT fk_recruiting_application_interview_question_application
        FOREIGN KEY (recruiting_application_id) REFERENCES public.recruiting_application (id);

CREATE INDEX idx_recruiting_round_evaluator_round_stage
    ON public.recruiting_round_evaluator (recruiting_round_id, stage);

CREATE INDEX idx_recruiting_round_interview_question_round_active_order
    ON public.recruiting_round_interview_question (recruiting_round_id, active, order_no, id);

CREATE INDEX idx_recruiting_application_interview_question_application_active_order
    ON public.recruiting_application_interview_question (recruiting_application_id, active, order_no, id);
