ALTER TABLE public.file_metadata
    ADD COLUMN confirmed_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN unreferenced_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN cleanup_claim_token UUID,
    ADD COLUMN cleanup_claimed_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN cleanup_attempts INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN cleanup_next_attempt_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN cleanup_failed_at TIMESTAMP(6) WITH TIME ZONE;

CREATE TABLE public.file_usage_owner
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usage_namespace VARCHAR(100)                NOT NULL,
    resource_key    VARCHAR(128)                NOT NULL,
    slot            VARCHAR(50)                 NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_file_usage_owner_coordinate
        UNIQUE (usage_namespace, resource_key, slot),
    CONSTRAINT ck_file_usage_owner_namespace
        CHECK (usage_namespace ~ '^[a-z][a-z0-9-]{0,31}(\.[a-z][a-z0-9-]{0,31})*$'),
    CONSTRAINT ck_file_usage_owner_resource_key
        CHECK (resource_key ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'),
    CONSTRAINT ck_file_usage_owner_slot
        CHECK (slot ~ '^[a-z][a-z0-9-]{0,49}$')
);

CREATE TABLE public.file_usage
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT                      NOT NULL,
    file_id    VARCHAR(255)                NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_file_usage_owner_file UNIQUE (owner_id, file_id),
    CONSTRAINT fk_file_usage_owner
        FOREIGN KEY (owner_id) REFERENCES public.file_usage_owner (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_usage_metadata
        FOREIGN KEY (file_id) REFERENCES public.file_metadata (id) ON DELETE RESTRICT
);

CREATE INDEX idx_file_usage_file_id ON public.file_usage (file_id);

CREATE TABLE public.file_usage_registry_cutover
(
    singleton   BOOLEAN                     PRIMARY KEY DEFAULT TRUE,
    status      VARCHAR(16)                 NOT NULL,
    verified_at TIMESTAMP(6) WITH TIME ZONE,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_file_usage_registry_cutover_singleton CHECK (singleton),
    CONSTRAINT ck_file_usage_registry_cutover_status CHECK (status IN ('PENDING', 'READY')),
    CONSTRAINT ck_file_usage_registry_cutover_verified CHECK (
        (status = 'PENDING' AND verified_at IS NULL)
        OR (status = 'READY' AND verified_at IS NOT NULL)
    )
);

INSERT INTO public.file_usage_registry_cutover
    (singleton, status, verified_at, created_at, updated_at)
VALUES (TRUE, 'PENDING', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

UPDATE public.file_metadata
SET confirmed_at = COALESCE(updated_at, created_at)
WHERE is_uploaded = TRUE
  AND confirmed_at IS NULL;

CREATE TABLE public.legacy_file_usage_snapshot
(
    usage_namespace VARCHAR(100) NOT NULL,
    resource_key    VARCHAR(128) NOT NULL,
    slot            VARCHAR(50)  NOT NULL,
    file_id         VARCHAR(255) NOT NULL
        REFERENCES public.file_metadata (id),
    is_uploaded     BOOLEAN      NOT NULL CHECK (is_uploaded),
    CHECK (btrim(file_id) <> ''),
    UNIQUE (usage_namespace, resource_key, slot, file_id)
);

INSERT INTO public.legacy_file_usage_snapshot
    (usage_namespace, resource_key, slot, file_id, is_uploaded)
SELECT
    legacy.usage_namespace,
    legacy.resource_key,
    legacy.slot,
    legacy.file_id,
    metadata.is_uploaded
FROM (
    SELECT 'member' AS usage_namespace,
           source.id::text AS resource_key,
           'profile-image' AS slot,
           source.profile_image_id::text AS file_id
    FROM public.member source
    WHERE source.profile_image_id IS NOT NULL

    UNION ALL

    SELECT 'organization.school', source.id::text, 'logo', source.logo_image_id::text
    FROM public.school source
    WHERE source.logo_image_id IS NOT NULL

    UNION ALL

    SELECT 'notice', source.notice_id::text, 'images', source.image_id::text
    FROM public.notice_image source
    WHERE source.image_id IS NOT NULL

    UNION ALL

    SELECT 'project', source.id::text, 'logo', source.logo_file_id::text
    FROM public.project source
    WHERE source.logo_file_id IS NOT NULL

    UNION ALL

    SELECT 'project', source.id::text, 'thumbnail', source.thumbnail_file_id::text
    FROM public.project source
    WHERE source.thumbnail_file_id IS NOT NULL

    UNION ALL

    SELECT 'form.answer', source.id::text, 'attachments', attachment.file_id::text
    FROM public.answer source
    CROSS JOIN LATERAL unnest(source.file_ids) AS attachment(file_id)

    UNION ALL

    SELECT 'chat.message', source.id::text, 'attachments', attachment.file_id::text
    FROM public.chat_message source
    CROSS JOIN LATERAL unnest(source.file_metadata_ids) AS attachment(file_id)

    UNION ALL

    SELECT 'organization.umc-product-member', source.id::text,
           'profile-image', source.profile_image_id::text
    FROM public.umc_product_member source
    WHERE source.profile_image_id IS NOT NULL

    UNION ALL

    SELECT 'certificate', source.id::text, 'file', source.file_id::text
    FROM public.certificate source
    WHERE source.file_id IS NOT NULL
) legacy
LEFT JOIN public.file_metadata metadata ON metadata.id = legacy.file_id;

INSERT INTO public.file_usage_owner
    (usage_namespace, resource_key, slot, created_at, updated_at)
SELECT usage_namespace, resource_key, slot, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM public.legacy_file_usage_snapshot
GROUP BY usage_namespace, resource_key, slot;

INSERT INTO public.file_usage (owner_id, file_id, created_at)
SELECT owner.id, snapshot.file_id, CURRENT_TIMESTAMP
FROM public.legacy_file_usage_snapshot snapshot
JOIN public.file_usage_owner owner
  ON owner.usage_namespace = snapshot.usage_namespace
 AND owner.resource_key = snapshot.resource_key
 AND owner.slot = snapshot.slot;

UPDATE public.file_metadata metadata
SET unreferenced_at = CASE
    WHEN EXISTS (
        SELECT 1
        FROM public.file_usage usage
        WHERE usage.file_id = metadata.id
    ) THEN NULL
    ELSE CURRENT_TIMESTAMP
END;

CREATE INDEX idx_file_metadata_cleanup_candidate
    ON public.file_metadata (cleanup_next_attempt_at, unreferenced_at, confirmed_at, created_at)
    WHERE cleanup_failed_at IS NULL;

DROP TABLE public.legacy_file_usage_snapshot;
