CREATE TABLE public.recruiting_season_track_quota
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_season_id  BIGINT                                  NOT NULL,
    track                 VARCHAR(255)                            NOT NULL,
    target_count          INTEGER                                 NOT NULL,
    CONSTRAINT pk_recruiting_season_track_quota PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_season_track_quota_season_track UNIQUE (recruiting_season_id, track),
    CONSTRAINT recruiting_season_track_quota_track_check CHECK (
        track IN ('PLAN', 'DESIGN', 'WEB_PRODUCT_ENGINEER', 'MOBILE_PRODUCT_ENGINEER')
    ),
    CONSTRAINT recruiting_season_track_quota_target_count_check CHECK (target_count >= 0),
    CONSTRAINT fk_recruiting_season_track_quota_season
        FOREIGN KEY (recruiting_season_id) REFERENCES public.recruiting_season (id)
);

ALTER TABLE public.recruiting_round
    ADD COLUMN recruitable_tracks            TEXT[]                   NOT NULL DEFAULT ARRAY[]::TEXT[],
    ADD COLUMN second_choice_enabled         BOOLEAN                  NOT NULL DEFAULT FALSE,
    ADD COLUMN document_start_at              TIMESTAMP WITH TIME ZONE,
    ADD COLUMN document_end_at                TIMESTAMP WITH TIME ZONE,
    ADD COLUMN document_result_published_at   TIMESTAMP WITH TIME ZONE,
    ADD COLUMN interview_required             BOOLEAN                  NOT NULL DEFAULT FALSE,
    ADD COLUMN interview_start_at             TIMESTAMP WITH TIME ZONE,
    ADD COLUMN interview_end_at               TIMESTAMP WITH TIME ZONE,
    ADD COLUMN final_result_published_at       TIMESTAMP WITH TIME ZONE,
    ADD COLUMN availability_form_id            BIGINT,
    ADD COLUMN announcement                    TEXT,
    ADD COLUMN contact_text                    TEXT;

ALTER TABLE public.recruiting_round
    ADD CONSTRAINT recruiting_round_recruitable_tracks_check CHECK (
        cardinality(recruitable_tracks) = 0
        OR (
            recruitable_tracks <@ ARRAY[
                'PLAN',
                'DESIGN',
                'WEB_PRODUCT_ENGINEER',
                'MOBILE_PRODUCT_ENGINEER'
            ]::TEXT[]
            AND cardinality(recruitable_tracks) > 0
            AND cardinality(array_positions(recruitable_tracks, 'PLAN')) <= 1
            AND cardinality(array_positions(recruitable_tracks, 'DESIGN')) <= 1
            AND cardinality(array_positions(recruitable_tracks, 'WEB_PRODUCT_ENGINEER')) <= 1
            AND cardinality(array_positions(recruitable_tracks, 'MOBILE_PRODUCT_ENGINEER')) <= 1
        )
    ) NOT VALID,
    ADD CONSTRAINT recruiting_round_schedule_check CHECK (
        (
            document_start_at IS NULL
            AND document_end_at IS NULL
            AND document_result_published_at IS NULL
            AND interview_start_at IS NULL
            AND interview_end_at IS NULL
            AND final_result_published_at IS NULL
            AND availability_form_id IS NULL
            AND NOT interview_required
        )
        OR (
            document_start_at IS NOT NULL
            AND document_end_at IS NOT NULL
            AND document_result_published_at IS NOT NULL
            AND final_result_published_at IS NOT NULL
            AND document_start_at < document_end_at
            AND document_end_at <= document_result_published_at
            AND (
                (
                    interview_required
                    AND interview_start_at IS NOT NULL
                    AND interview_end_at IS NOT NULL
                    AND document_result_published_at <= interview_start_at
                    AND interview_start_at < interview_end_at
                    AND interview_end_at <= final_result_published_at
                )
                OR (
                    NOT interview_required
                    AND interview_start_at IS NULL
                    AND interview_end_at IS NULL
                    AND availability_form_id IS NULL
                    AND document_result_published_at <= final_result_published_at
                )
            )
        )
    ) NOT VALID;

ALTER TABLE public.recruiting_round
    VALIDATE CONSTRAINT recruiting_round_recruitable_tracks_check;

ALTER TABLE public.recruiting_round
    VALIDATE CONSTRAINT recruiting_round_schedule_check;
