ALTER TABLE umc_product_member ADD COLUMN name VARCHAR(30);
ALTER TABLE umc_product_member ADD COLUMN nickname VARCHAR(20);
ALTER TABLE umc_product_member ADD COLUMN school_id BIGINT;

UPDATE umc_product_member u
SET name = m.name,
    nickname = m.nickname,
    school_id = m.school_id
FROM member m
WHERE m.id = u.member_id;

ALTER TABLE umc_product_member ALTER COLUMN name SET NOT NULL;
ALTER TABLE umc_product_member ALTER COLUMN nickname SET NOT NULL;

CREATE TABLE umc_product_member_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    umc_product_member_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    account_type VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_umc_product_member_account_member
        FOREIGN KEY (umc_product_member_id) REFERENCES umc_product_member(id) ON DELETE RESTRICT,
    CONSTRAINT fk_umc_product_member_account_login_member
        FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE RESTRICT,
    CONSTRAINT uk_umc_product_member_account_member_id UNIQUE (member_id),
    CONSTRAINT ck_umc_product_member_account_type CHECK (account_type IN ('PROVISIONED', 'LINKED'))
);

CREATE INDEX ix_umc_product_member_account_umc_member
    ON umc_product_member_account (umc_product_member_id);

INSERT INTO umc_product_member_account (
    umc_product_member_id,
    member_id,
    account_type,
    created_at,
    updated_at
)
SELECT id, member_id, 'LINKED', NOW(), NOW()
FROM umc_product_member;

ALTER TABLE umc_product_member DROP CONSTRAINT uk_umc_product_member_member_id;
ALTER TABLE umc_product_member DROP COLUMN member_id;
