CREATE TABLE public.recruiting_season
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    gisu_id    BIGINT                                  NOT NULL,
    school_id  BIGINT                                  NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_recruiting_season PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_season_gisu_school UNIQUE (gisu_id, school_id),
    CONSTRAINT recruiting_season_status_check CHECK (
        status IN ('DRAFT', 'ACTIVE', 'CLOSED')
    )
);

CREATE TABLE public.recruiting_round
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_season_id BIGINT                                  NOT NULL,
    type                 VARCHAR(255)                            NOT NULL,
    round_no             INTEGER                                 NOT NULL,
    status               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_recruiting_round PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_round_season_type_no UNIQUE (recruiting_season_id, type, round_no),
    CONSTRAINT recruiting_round_type_check CHECK (
        type IN ('REGULAR', 'ADDITIONAL')
    ),
    CONSTRAINT recruiting_round_status_check CHECK (
        status IN ('DRAFT', 'OPEN', 'CLOSED')
    ),
    CONSTRAINT recruiting_round_no_check CHECK (round_no >= 1)
);

CREATE TABLE public.recruiting_application_form
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_round_id  BIGINT                                  NOT NULL,
    form_id              BIGINT                                  NOT NULL,
    track                VARCHAR(255)                            NOT NULL,
    status               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_recruiting_application_form PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_application_form_round_form UNIQUE (recruiting_round_id, form_id),
    CONSTRAINT recruiting_application_form_track_check CHECK (
        track IN (
            'PLAN',
            'DESIGN',
            'WEB_PRODUCT_ENGINEER',
            'MOBILE_PRODUCT_ENGINEER',
            'INFRA_PLUS'
        )
    ),
    CONSTRAINT recruiting_application_form_status_check CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'CLOSED')
    )
);

CREATE TABLE public.recruiting_application
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                      TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at                      TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_round_id             BIGINT                                  NOT NULL,
    recruiting_application_form_id  BIGINT                                  NOT NULL,
    form_response_id                BIGINT                                  NOT NULL,
    applicant_member_id             BIGINT,
    applicant_identity_key          VARCHAR(128)                            NOT NULL,
    application_no                  VARCHAR(64)                             NOT NULL,
    masked_email                    VARCHAR(255),
    status                          VARCHAR(255)                            NOT NULL,
    registration_status             VARCHAR(255)                            NOT NULL,
    submitted_at                    TIMESTAMP WITH TIME ZONE,
    status_changed_member_id        BIGINT,
    status_change_reason            VARCHAR(255),
    status_changed_at               TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_recruiting_application PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_application_application_no UNIQUE (application_no),
    CONSTRAINT uk_recruiting_application_form_response UNIQUE (form_response_id),
    CONSTRAINT recruiting_application_status_check CHECK (
        status IN (
            'DRAFT',
            'SUBMITTED',
            'DOCUMENT_PASSED',
            'DOCUMENT_FAILED',
            'INTERVIEW_ASSIGNED',
            'INTERVIEW_SKIPPED',
            'FINAL_PASSED',
            'FINAL_FAILED',
            'CANCELLED'
        )
    ),
    CONSTRAINT recruiting_application_registration_status_check CHECK (
        registration_status IN ('NOT_READY', 'READY', 'REGISTERED')
    )
);

ALTER TABLE public.recruiting_round
    ADD CONSTRAINT fk_recruiting_round_season
        FOREIGN KEY (recruiting_season_id) REFERENCES public.recruiting_season (id);

ALTER TABLE public.recruiting_application_form
    ADD CONSTRAINT fk_recruiting_application_form_round
        FOREIGN KEY (recruiting_round_id) REFERENCES public.recruiting_round (id);

ALTER TABLE public.recruiting_application
    ADD CONSTRAINT fk_recruiting_application_round
        FOREIGN KEY (recruiting_round_id) REFERENCES public.recruiting_round (id);

ALTER TABLE public.recruiting_application
    ADD CONSTRAINT fk_recruiting_application_form
        FOREIGN KEY (recruiting_application_form_id) REFERENCES public.recruiting_application_form (id);

CREATE UNIQUE INDEX uk_recruiting_application_active_round_identity
    ON public.recruiting_application (recruiting_round_id, applicant_identity_key)
    WHERE status IN (
        'DRAFT',
        'SUBMITTED',
        'DOCUMENT_PASSED',
        'INTERVIEW_ASSIGNED',
        'INTERVIEW_SKIPPED',
        'FINAL_PASSED'
    );

CREATE INDEX ix_recruiting_application_status
    ON public.recruiting_application (status);
