CREATE TABLE public.member_system_role
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) with time zone             NOT NULL,
    updated_at timestamp(6) with time zone             NOT NULL,
    member_id  bigint                                  NOT NULL,
    role_type  character varying(50)                   NOT NULL,
    CONSTRAINT member_system_role_pkey PRIMARY KEY (id),
    CONSTRAINT uk_member_system_role_member_role UNIQUE (member_id, role_type),
    CONSTRAINT member_system_role_role_type_check CHECK (
        (role_type)::text = ANY (ARRAY[
            ('SUPER_ADMIN'::character varying)::text
        ])
    )
);

CREATE INDEX idx_member_system_role_member_id
    ON public.member_system_role (member_id);

ALTER TABLE ONLY public.member_system_role
    ADD CONSTRAINT fk_member_system_role_member
        FOREIGN KEY (member_id) REFERENCES public.member (id);

INSERT INTO public.member_system_role (created_at, updated_at, member_id, role_type)
SELECT DISTINCT
    now(),
    now(),
    c.member_id,
    'SUPER_ADMIN'
FROM public.challenger_role cr
JOIN public.challenger c ON c.id = cr.challenger_id
WHERE cr.role_type = 'SUPER_ADMIN'
ON CONFLICT (member_id, role_type) DO NOTHING;

DELETE FROM public.challenger_role
WHERE role_type = 'SUPER_ADMIN';

ALTER TABLE public.challenger_role
    DROP CONSTRAINT challenger_role_role_type_check;

ALTER TABLE public.challenger_role
    ADD CONSTRAINT challenger_role_role_type_check CHECK (
        (role_type)::text = ANY (ARRAY[
            ('CENTRAL_PRESIDENT'::character varying)::text,
            ('CENTRAL_VICE_PRESIDENT'::character varying)::text,
            ('CENTRAL_OPERATING_TEAM_MEMBER'::character varying)::text,
            ('CENTRAL_EDUCATION_TEAM_MEMBER'::character varying)::text,
            ('CHAPTER_PRESIDENT'::character varying)::text,
            ('SCHOOL_PRESIDENT'::character varying)::text,
            ('SCHOOL_VICE_PRESIDENT'::character varying)::text,
            ('SCHOOL_PART_LEADER'::character varying)::text,
            ('SCHOOL_ETC_ADMIN'::character varying)::text
        ])
    );
